ALTER TABLE APP.T_QUESTIONS DROP CONSTRAINT TQUESTIONSSURVEYID
ALTER TABLE APP.T_ANSWERS DROP CONSTRAINT TANSWERSQUESTIONID
DROP TABLE APP.T_USERS
DROP TABLE APP.T_SURVEYS
DROP TABLE APP.T_QUESTIONS
DROP TABLE APP.T_ANSWERS
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
